# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:1 --redirect --dataset_name MO-HalfCheetah-v2_50000_amateur_narrow &
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:3 --redirect --dataset_name MO-HalfCheetah-v2_50000_amateur_uniform &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:2 --redirect --dataset_name MO-HalfCheetah-v2_50000_amateur_wide &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:2 --redirect --dataset_name MO-HalfCheetah-v2_50000_expert_narrow &
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:3 --redirect --dataset_name MO-HalfCheetah-v2_50000_expert_uniform &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:3 --redirect --dataset_name MO-HalfCheetah-v2_50000_expert_wide &
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:4 --redirect --dataset_name MO-Swimmer-v2_50000_amateur_uniform &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:4 --redirect --dataset_name MO-Swimmer-v2_50000_expert_narrow &
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:4 --redirect --dataset_name MO-Swimmer-v2_50000_expert_uniform &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:5 --redirect --dataset_name MO-Swimmer-v2_50000_expert_wide & wait
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:5 --redirect --dataset_name MO-Ant-v2_50000_amateur_uniform &
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:5 --redirect --dataset_name MO-Ant-v2_50000_expert_uniform & wait
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:3 --redirect --dataset_name MO-Walker2d-v2_50000_expert_uniform &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:2 --redirect --dataset_name MO-Walker2d-v2_50000_expert_wide &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:3 --redirect --dataset_name MO-Walker2d-v2_50000_expert_narrow &
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:3 --redirect --dataset_name MO-Walker2d-v2_50000_amateur_uniform &
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:4 --redirect --dataset_name MO-Hopper-v2_50000_expert_uniform &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:4 --redirect --dataset_name MO-Hopper-v2_50000_expert_wide &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:5 --redirect --dataset_name MO-Hopper-v2_50000_expert_narrow &
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:4 --redirect --dataset_name MO-Hopper-v2_50000_amateur_uniform &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:1 --redirect --dataset_name MO-Hopper-v3_50000_expert_narrow &
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:5 --redirect --dataset_name MO-Hopper-v3_50000_amateur_uniform &
# nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:2 --redirect --dataset_name MO-Hopper-v3_50000_expert_wide &
nohup python -u dev/mo_pipelines/mo_dd_dyna.py --device=cuda:5 --redirect --dataset_name MO-Hopper-v3_50000_expert_uniform & wait