pipeline_name: "diffuser_d4rl_mujoco"
env_name: "walker2d-medium-expert-v2"
seed: 0

# Dataset
terminal_penalty: -100
discount: 0.997

# Training
n_gradient_steps_diffusion: 1000000
n_gradient_steps_classifier: 200000
batch_size: 256
action_weight: 10
save_interval: 100000

# Planning
horizon: 32
w_cg: 0.0001
sample_steps: 10
use_ema: true
solver: "euler"
n_elites: 128
